# Local Development Configuration
# Usage: docker-compose up
services:
  # 🌐 Web App (frontend) - Direct access for local development
  frontend:
    build: .
    container_name: spark-to-bloom-app
    restart: unless-stopped
    environment:
      - ENVIRONMENT=development
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.spark.rule=Host(`sparktobloom.com`)"
      - "traefik.http.routers.spark.entrypoints=websecure"
      - "traefik.http.routers.spark.tls=true"
      - "traefik.http.services.spark.loadbalancer.server.port=5000"
    ports:
      - "5000:5000"  # Direct port mapping for local development
    networks:
      - traefik-global
      - default

networks:
  traefik-global:
    external: true
  default:
    external: false
